/*
 * $Id: $
 * 
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 * 
 * $Copyright: Copyright 2010 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 */

#ifndef __BMD_REMAP_H__
#define __BMD_REMAP_H__

#include <bmd_config.h>


/*******************************************************************************
 *
 * The following #defines allow remapping of the BMD API based on the value of 
 * BMD_CONFIG_API_PREFIX when it is defined. This will most often be used to
 * eliminate the intermediate API dispatch mechanism when not needed.
 *
 ******************************************************************************/

#if defined(BMD_CONFIG_API_PREFIX) && !defined(BMD_CONFIG_API_PREFIX_DISABLE)

#define __BMD_API_CONCAT(x,y) x##y
#define _BMD_API_CONCAT(x,y) __BMD_API_CONCAT(x,y)

#define bmd_attach _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_attach)
#define bmd_detach _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_detach)
#define bmd_reset _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_reset)
#define bmd_init _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_init)
#define bmd_port_mode_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_mode_set)
#define bmd_port_mode_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_mode_get)
#define bmd_port_mode_update _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_mode_update)
#define bmd_vlan_create _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_vlan_create)
#define bmd_vlan_port_add _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_vlan_port_add)
#define bmd_vlan_port_remove _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_vlan_port_remove)
#define bmd_vlan_port_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_vlan_port_get)
#define bmd_vlan_destroy _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_vlan_destroy)
#define bmd_port_vlan_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_vlan_set)
#define bmd_port_vlan_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_vlan_get)
#define bmd_port_stp_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_stp_set)
#define bmd_port_stp_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_stp_get)
#define bmd_switching_init _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_switching_init)
#define bmd_port_mac_addr_add _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_mac_addr_add)
#define bmd_port_mac_addr_remove _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_mac_addr_remove)
#define bmd_cpu_mac_addr_add _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cpu_mac_addr_add)
#define bmd_cpu_mac_addr_remove _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cpu_mac_addr_remove)
#define bmd_mcast_mac_addr_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_mcast_mac_addr_set)
#define bmd_mcast_mac_addr_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_mcast_mac_addr_get)
#define bmd_tx _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_tx)
#define bmd_rx_start _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_rx_start)
#define bmd_rx_poll _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_rx_poll)
#define bmd_rx_stop _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_rx_stop)
#define bmd_stat_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_stat_get)
#define bmd_stat_clear _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_stat_clear)
#define bmd_test_interrupt_assert _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_test_interrupt_assert)
#define bmd_test_interrupt_clear _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_test_interrupt_clear)
#define bmd_download _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_download)
#define bmd_switch_control_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_switch_control_set)
#define bmd_switch_control_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_switch_control_get)
#define bmd_switch_control_priority_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_switch_control_priority_set)
#define bmd_switch_control_priority_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_switch_control_priority_get)
#define bmd_port_pause_capability_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_pause_capability_set)
#define bmd_port_pause_capability_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_pause_capability_get)
#define bmd_port_rate_ingress_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_rate_ingress_set)
#define bmd_port_rate_ingress_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_rate_ingress_get)
#define bmd_port_rate_egress_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_rate_egress_set)
#define bmd_port_rate_egress_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_rate_egress_get)
#define bmd_port_replace_egress_tag_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_replace_egress_tag_set)
#define bmd_port_replace_egress_tag_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_replace_egress_tag_get)
#define bmd_port_vlan_priority_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_vlan_priority_set)
#define bmd_port_vlan_priority_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_vlan_priority_get)
#define bmd_port_tag_mangle_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_tag_mangle_set)
#define bmd_port_tag_mangle_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_tag_mangle_get)
#define bmd_port_pbvlanmap_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_pbvlanmap_set)
#define bmd_port_pbvlanmap_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_pbvlanmap_get)
#define bmd_port_traffic_control_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_traffic_control_set)
#define bmd_port_traffic_control_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_traffic_control_get)
#define bmd_port_jumbo_control_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_jumbo_control_set)
#define bmd_port_jumbo_control_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_port_jumbo_control_get)
#define bmd_cosq_config_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_config_set)
#define bmd_cosq_config_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_config_get)
#define bmd_cosq_priority_method_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_priority_method_set)
#define bmd_cosq_priority_method_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_priority_method_get)
#define bmd_cosq_sched_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_sched_set)
#define bmd_cosq_sched_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_sched_get)
#define bmd_cosq_wrr_weight_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_wrr_weight_set)
#define bmd_cosq_wrr_weight_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_wrr_weight_get)
#define bmd_cosq_port_mapping_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_port_mapping_set)
#define bmd_cosq_port_mapping_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_port_mapping_get)
#define bmd_cosq_dscp_priority_mapping_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_dscp_priority_mapping_set)
#define bmd_cosq_dscp_priority_mapping_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_dscp_priority_mapping_get)
#define bmd_cosq_txq_selection_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_txq_selection_set)
#define bmd_cosq_txq_selection_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_txq_selection_get)
#define bmd_cosq_rxchannel_mapping_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_rxchannel_mapping_set)
#define bmd_cosq_rxchannel_mapping_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_rxchannel_mapping_get)
#define bmd_cosq_txchannel_mapping_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_txchannel_mapping_set)
#define bmd_cosq_txchannel_mapping_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_cosq_txchannel_mapping_get)
#define bmd_packet_padding_set _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_packet_padding_set)
#define bmd_packet_padding_get _BMD_API_CONCAT(BMD_CONFIG_API_PREFIX,bmd_packet_padding_get)

#endif /* BMD_CONFIG_API_PREFIX */

#endif /* __BMD_REMAP_H__ */
