/*
 * Automatically generated C config: don't edit
 */
#define RTCONFIG_OPTIMIZE_SHARED_LIBS 1
#define RTCONFIG_L2TP 1
#define RTCONFIG_PPTP 1
#define RTCONFIG_EAPOL 1
#undef RTCONFIG_PPTPD
#undef RTCONFIG_ACCEL_PPTPD
#define RTCONFIG_HTTPS 1
#define RTCONFIG_SSH 1
#define RTCONFIG_CIFS 1
#define RTCONFIG_JFFS2 1
#define RTCONFIG_JFFSV1 1
#define RTCONFIG_ZEBRA 1
#define RTCONFIG_DDNS 1
#define RTCONFIG_L7 1
#undef RTCONFIG_LZO
#undef RTCONFIG_IPV6
#undef RTCONFIG_EBTABLES
#undef RTCONFIG_EMF
#undef RTCONFIG_FANCTRL
#undef RTCONFIG_BCMWL6
#undef RTCONFIG_WIRELESSWAN
#undef RTCONFIG_W3N
#undef RTCONFIG_WIRELESSREPEATER
#undef RTCONFIG_PROXYSTA
#undef RTCONFIG_OLD_PARENTALCTRL
#undef RTCONFIG_PARENTALCTRL
#undef RTCONFIG_DSL
#undef RTCONFIG_DSL_ANNEX_B
#undef RTCONFIG_DUALWAN
#define RTCONFIG_USB 1
#undef RTCONFIG_MEDIA_SERVER
#undef RTCONFIG_CLOUDSYNC
#define RTCONFIG_FTP 1
#undef RTCONFIG_FTP_SSL
#undef RTCONFIG_WEBDAV
#define RTCONFIG_SAMBASRV 1
#undef RTCONFIG_SAMBA3
#undef RTCONFIG_USB_EXTRAS
#undef RTCONFIG_NTFS
#undef RTCONFIG_NTFS3G
#undef RTCONFIG_USB_PRINTER
#undef RTCONFIG_USB_MODEM
#undef RTCONFIG_BRCM_USBAP
#undef RTCONFIG_APP_PREINSTALLED
#undef RTCONFIG_APP_NETINSTALLED
#define RTCONFIG_DNSMASQ 1
#undef RTCONFIG_RALINK
#undef RTCONFIG_ODMPID
#undef CONFIG_LIBBCM
#undef CONFIG_LIBUPNP
#define RTCONFIG_WPS 1
#undef RTCONFIG_SHP
#undef RTCONFIG_SFP
#undef RTCONFIG_STRACE
#undef RTCONFIG_4M_SFP
#undef RTCONFIG_16M_RAM_SFP
#undef RTCONFIG_GROCTRL
#undef RTCONFIG_LANWAN_LED
#undef RTCONFIG_SWMODE_SWITCH
#undef RTCONFIG_WIRELESS_SWITCH
#undef RTCONFIG_AUTODICT
#undef RTCONFIG_ISP_METER
#undef RTCONFIG_NVRAM_64K
#undef RTCONFIG_GDB
#undef RTCONFIG_USB_XHCI
#undef RTCONFIG_WLMODULE_RT3090_AP
#undef RTCONFIG_WLMODULE_RT3352_INIC_MII
#undef RTCONFIG_PSISTLOG
#undef RTCONFIG_DUAL_TRX
