/*******************************************************************************
 *
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated from the registers file.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Copyright: Copyright 2013 Broadcom Corporation.
 * This program is the proprietary software of Broadcom Corporation
 * and/or its licensors, and may only be used, duplicated, modified
 * or distributed pursuant to the terms and conditions of a separate,
 * written license agreement executed between you and Broadcom
 * (an "Authorized License").  Except as set forth in an Authorized
 * License, Broadcom grants no license (express or implied), right
 * to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software
 * and all intellectual property rights therein.  IF YOU HAVE
 * NO AUTHORIZED LICENSE, THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE
 * IN ANY WAY, AND SHOULD IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE
 * ALL USE OF THE SOFTWARE.  
 *  
 * Except as expressly set forth in the Authorized License,
 *  
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use
 * all reasonable efforts to protect the confidentiality thereof,
 * and to use this information only in connection with your use of
 * Broadcom integrated circuit products.
 *  
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS
 * PROVIDED "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES,
 * REPRESENTATIONS OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY,
 * OR OTHERWISE, WITH RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY
 * DISCLAIMS ANY AND ALL IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY,
 * NONINFRINGEMENT, FITNESS FOR A PARTICULAR PURPOSE, LACK OF VIRUSES,
 * ACCURACY OR COMPLETENESS, QUIET ENJOYMENT, QUIET POSSESSION OR
 * CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE ENTIRE RISK ARISING
 * OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 * 
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL
 * BROADCOM OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL,
 * INCIDENTAL, SPECIAL, INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER
 * ARISING OUT OF OR IN ANY WAY RELATING TO YOUR USE OF OR INABILITY
 * TO USE THE SOFTWARE EVEN IF BROADCOM HAS BEEN ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN EXCESS OF
 * THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR USD 1.00,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING
 * ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.$
 *
 * Symbol table file for HiGig module headers.
 * This symbol table is used by the Broadcom debug shell.
 *
 ******************************************************************************/


#include <cdk/cdk_symbols.h>

/* No symbols will be compiled unless this is defined. */
#if CDK_CONFIG_INCLUDE_CHIP_SYMBOLS == 1
/*******************************************************************************
 *
 * If CDK_CONFIG_INCLUDE_FIELD_INFO is 1, then symbol information
 * necessary to encode and decode the individual fields will be available.
 *
 * Field information can be compiled out in the interest of saving code space.
 *
 ******************************************************************************/
#if CDK_CONFIG_INCLUDE_FIELD_INFO == 1

static uint32_t HIGIG_fields[] =
{
    /* VC_LABEL:0:19 */
    CDK_SYMBOL_FIELD_ENCODE(36, 19, 0),
    /* CLASSIFICATION_TAG:16:31 */
    CDK_SYMBOL_FIELD_ENCODE(0, 31, 16),
    /* LABEL_PRESENT:20:20 */
    CDK_SYMBOL_FIELD_ENCODE(17, 20, 20),
    /* L3:21:21 */
    CDK_SYMBOL_FIELD_ENCODE(16, 21, 21),
    /* DST_MODID_5:22:22 */
    CDK_SYMBOL_FIELD_ENCODE(4, 22, 22),
    /* SRC_MODID_5:23:23 */
    CDK_SYMBOL_FIELD_ENCODE(29, 23, 23),
    /* MIRROR:24:24 */
    CDK_SYMBOL_FIELD_ENCODE(20, 24, 24),
    /* MIRROR_DONE:25:25 */
    CDK_SYMBOL_FIELD_ENCODE(21, 25, 25),
    /* MIRROR_ONLY:26:26 */
    CDK_SYMBOL_FIELD_ENCODE(22, 26, 26),
    /* INGRESS_TAGGED:27:27 */
    CDK_SYMBOL_FIELD_ENCODE(15, 27, 27),
    /* DST_TGID:28:30 */
    CDK_SYMBOL_FIELD_ENCODE(11, 30, 28),
    /* DST_T:31:31 */
    CDK_SYMBOL_FIELD_ENCODE(10, 31, 31),
    /* DST_MODID_LS:32:36 */
    CDK_SYMBOL_FIELD_ENCODE(6, 36, 32),
    /* CNG:37:37 */
    CDK_SYMBOL_FIELD_ENCODE(1, 37, 37),
    /* HEADER_TYPE:38:39 */
    CDK_SYMBOL_FIELD_ENCODE(13, 39, 38),
    /* PRIORITY:40:42 */
    CDK_SYMBOL_FIELD_ENCODE(27, 42, 40),
    /* DST_PORT:43:47 */
    CDK_SYMBOL_FIELD_ENCODE(8, 47, 43),
    /* SRC_PORT_TGID:48:53 */
    CDK_SYMBOL_FIELD_ENCODE(33, 53, 48),
    /* PFM:54:55 */
    CDK_SYMBOL_FIELD_ENCODE(24, 55, 54),
    /* OPCODE:56:58 */
    CDK_SYMBOL_FIELD_ENCODE(23, 58, 56),
    /* SRC_MODID_LS:59:63 */
    CDK_SYMBOL_FIELD_ENCODE(31, 63, 59),
    /* VTAG:64:79 */
    CDK_SYMBOL_FIELD_ENCODE(37, 79, 64),
    /* DST_MODID_6:80:80 */
    CDK_SYMBOL_FIELD_ENCODE(5, 80, 80),
    /* SRC_MODID_6:81:81 */
    CDK_SYMBOL_FIELD_ENCODE(30, 81, 81),
    /* HDR_EXT_LEN:82:84 */
    CDK_SYMBOL_FIELD_ENCODE(12, 84, 82),
    /* CNG1:85:85 */
    CDK_SYMBOL_FIELD_ENCODE(2, 85, 85),
    /* HGI:86:87 */
    CDK_SYMBOL_FIELD_ENCODE(14, 87, 86),
    /* START:88:95 */
    CDK_SYMBOL_FIELD_FLAG_LAST | CDK_SYMBOL_FIELD_ENCODE(34, 95, 88)
};
static uint32_t HIGIG2_fields[] =
{
    /* PPD_DATA:0:63 */
    CDK_SYMBOL_FIELD_ENCODE(25, 63, 0),
    /* PPD0:RSVD_4_0:0:4 */
    CDK_SYMBOL_FIELD_ENCODE(55, 4, 0),
    /* PPD0:HDR_EXT_LEN:5:7 */
    CDK_SYMBOL_FIELD_ENCODE(40, 7, 5),
    /* PPD0:OPCODE:8:10 */
    CDK_SYMBOL_FIELD_ENCODE(49, 10, 8),
    /* PPD0:PRESERVE_DOT1P:11:11 */
    CDK_SYMBOL_FIELD_ENCODE(53, 11, 11),
    /* PPD0:PRESERVE_DSCP:12:12 */
    CDK_SYMBOL_FIELD_ENCODE(54, 12, 12),
    /* PPD0:SRC_T:13:13 */
    CDK_SYMBOL_FIELD_ENCODE(56, 13, 13),
    /* PPD0:PFM:14:15 */
    CDK_SYMBOL_FIELD_ENCODE(52, 15, 14),
    /* PPD0:VID_LOW:16:23 */
    CDK_SYMBOL_FIELD_ENCODE(60, 23, 16),
    /* PPD0:VID_HIGH:24:31 */
    CDK_SYMBOL_FIELD_ENCODE(59, 31, 24),
    /* PPD0:VC_LABEL:32:47 */
    CDK_SYMBOL_FIELD_ENCODE(57, 47, 32),
    /* PPD0:MIRROR_CLASSIFICATION_TAG:36:51 */
    CDK_SYMBOL_FIELD_ENCODE(46, 51, 36),
    /* PPD0:ORIG_SRC_PORT:36:43 */
    CDK_SYMBOL_FIELD_ENCODE(51, 43, 36),
    /* PPD0:ORIG_SRC_MODID:44:51 */
    CDK_SYMBOL_FIELD_ENCODE(50, 51, 44),
    /* PPD0:VC_LABEL_19_16:48:51 */
    CDK_SYMBOL_FIELD_ENCODE(58, 51, 48),
    /* PPD0:LABEL_PRESENT:52:52 */
    CDK_SYMBOL_FIELD_ENCODE(44, 52, 52),
    /* PPD0:L3:53:53 */
    CDK_SYMBOL_FIELD_ENCODE(42, 53, 53),
    /* PPD0:LABEL_OVERLAY_TYPE:54:55 */
    CDK_SYMBOL_FIELD_ENCODE(43, 55, 54),
    /* PPD0:MIRROR:56:56 */
    CDK_SYMBOL_FIELD_ENCODE(45, 56, 56),
    /* PPD0:MIRROR_DONE:57:57 */
    CDK_SYMBOL_FIELD_ENCODE(47, 57, 57),
    /* PPD0:MIRROR_ONLY:58:58 */
    CDK_SYMBOL_FIELD_ENCODE(48, 58, 58),
    /* PPD0:INGRESS_TAGGED:59:59 */
    CDK_SYMBOL_FIELD_ENCODE(41, 59, 59),
    /* PPD0:DST_TGID:60:62 */
    CDK_SYMBOL_FIELD_ENCODE(39, 62, 60),
    /* PPD0:DST_T:63:63 */
    CDK_SYMBOL_FIELD_ENCODE(38, 63, 63),
    /* PPD1:RSVD_4_0:0:4 */
    CDK_SYMBOL_FIELD_ENCODE(67, 4, 0),
    /* PPD1:HDR_EXT_LEN:5:7 */
    CDK_SYMBOL_FIELD_ENCODE(62, 7, 5),
    /* PPD1:OPCODE:8:10 */
    CDK_SYMBOL_FIELD_ENCODE(63, 10, 8),
    /* PPD1:RSVD_12_11:11:12 */
    CDK_SYMBOL_FIELD_ENCODE(65, 12, 11),
    /* PPD1:SRC_T:13:13 */
    CDK_SYMBOL_FIELD_ENCODE(68, 13, 13),
    /* PPD1:PFM:14:15 */
    CDK_SYMBOL_FIELD_ENCODE(64, 15, 14),
    /* PPD1:VID_LOW:16:23 */
    CDK_SYMBOL_FIELD_ENCODE(70, 23, 16),
    /* PPD1:VID_HIGH:24:31 */
    CDK_SYMBOL_FIELD_ENCODE(69, 31, 24),
    /* PPD1:RSVD_48_32:32:47 */
    CDK_SYMBOL_FIELD_ENCODE(66, 47, 32),
    /* PPD1:CLASSIFICATION_TAG:48:63 */
    CDK_SYMBOL_FIELD_ENCODE(61, 63, 48),
    /* PPD2:SOURCE_TYPE:0:0 */
    CDK_SYMBOL_FIELD_ENCODE(84, 0, 0),
    /* PPD2:DEST_TYPE:1:1 */
    CDK_SYMBOL_FIELD_ENCODE(71, 1, 1),
    /* PPD2:PRESERVE_DOT1P:2:2 */
    CDK_SYMBOL_FIELD_ENCODE(80, 2, 2),
    /* PPD2:PRESERVE_DSCP:3:3 */
    CDK_SYMBOL_FIELD_ENCODE(81, 3, 3),
    /* PPD2:VNI_HIGH:4:5 */
    CDK_SYMBOL_FIELD_ENCODE(86, 5, 4),
    /* PPD2:RSVD_7_6:6:7 */
    CDK_SYMBOL_FIELD_ENCODE(83, 7, 6),
    /* PPD2:OPCODE:8:10 */
    CDK_SYMBOL_FIELD_ENCODE(79, 10, 8),
    /* PPD2:RSVD_11:11:11 */
    CDK_SYMBOL_FIELD_ENCODE(82, 11, 11),
    /* PPD2:LAG_FAILOVER:12:12 */
    CDK_SYMBOL_FIELD_ENCODE(76, 12, 12),
    /* PPD2:DO_NOT_LEARN:13:13 */
    CDK_SYMBOL_FIELD_ENCODE(73, 13, 13),
    /* PPD2:DO_NOT_MODIFY:14:14 */
    CDK_SYMBOL_FIELD_ENCODE(74, 14, 14),
    /* PPD2:MIRROR:15:15 */
    CDK_SYMBOL_FIELD_ENCODE(77, 15, 15),
    /* PPD2:SOURCE_VP:16:31 */
    CDK_SYMBOL_FIELD_ENCODE(85, 31, 16),
    /* PPD2:DEST_VP:32:47 */
    CDK_SYMBOL_FIELD_ENCODE(72, 47, 32),
    /* PPD2:VNI_LOW:48:55 */
    CDK_SYMBOL_FIELD_ENCODE(87, 55, 48),
    /* PPD2:VNI_MID:56:57 */
    CDK_SYMBOL_FIELD_ENCODE(88, 57, 56),
    /* PPD2:FWD_TYPE:58:62 */
    CDK_SYMBOL_FIELD_ENCODE(75, 62, 58),
    /* PPD2:MULTIPOINT:63:63 */
    CDK_SYMBOL_FIELD_ENCODE(78, 63, 63),
    /* PPD3:PPD3_CONTAINER_TYPE:0:3 */
    CDK_SYMBOL_FIELD_ENCODE(91, 3, 0),
    /* PPD3:RSVD_7_4:4:7 */
    CDK_SYMBOL_FIELD_ENCODE(96, 7, 4),
    /* PPD3:OPCODE:8:10 */
    CDK_SYMBOL_FIELD_ENCODE(90, 10, 8),
    /* PPD3:SOURCE_TYPE:11:11 */
    CDK_SYMBOL_FIELD_ENCODE(98, 11, 11),
    /* PPD3:RSVD_28:12:12 */
    CDK_SYMBOL_FIELD_ENCODE(95, 12, 12),
    /* PPD3:DO_NOT_LEARN:13:13 */
    CDK_SYMBOL_FIELD_ENCODE(89, 13, 13),
    /* PPD3:PRESERVE_DOT1P:14:14 */
    CDK_SYMBOL_FIELD_ENCODE(93, 14, 14),
    /* PPD3:PRESERVE_DSCP:15:15 */
    CDK_SYMBOL_FIELD_ENCODE(94, 15, 15),
    /* PPD3:SOURCE_INFO:16:31 */
    CDK_SYMBOL_FIELD_ENCODE(97, 31, 16),
    /* PPD3:PPD3_DATA_CONTAINER:32:63 */
    CDK_SYMBOL_FIELD_ENCODE(92, 63, 32),
    /* PPD_TYPE:64:66 */
    CDK_SYMBOL_FIELD_ENCODE(26, 66, 64),
    /* DP:70:71 */
    CDK_SYMBOL_FIELD_ENCODE(3, 71, 70),
    /* LBID:72:79 */
    CDK_SYMBOL_FIELD_ENCODE(18, 79, 72),
    /* SRC_PID:80:87 */
    CDK_SYMBOL_FIELD_ENCODE(32, 87, 80),
    /* SRC_MODID:88:95 */
    CDK_SYMBOL_FIELD_ENCODE(28, 95, 88),
    /* DST_PORT_MGIDL:96:103 */
    CDK_SYMBOL_FIELD_ENCODE(9, 103, 96),
    /* DST_MODID_MGIDH:104:111 */
    CDK_SYMBOL_FIELD_ENCODE(7, 111, 104),
    /* TC:112:115 */
    CDK_SYMBOL_FIELD_ENCODE(35, 115, 112),
    /* MCST:116:116 */
    CDK_SYMBOL_FIELD_ENCODE(19, 116, 116),
    /* START:120:127 */
    CDK_SYMBOL_FIELD_FLAG_LAST | CDK_SYMBOL_FIELD_ENCODE(34, 127, 120)
};



/*******************************************************************************
 *
 * The following is the field name table.
 *
 *******************************************************************************/
#if CDK_CONFIG_INCLUDE_FIELD_NAMES == 1
const char* higig_fields[] = 
{
    "CLASSIFICATION_TAG",
    "CNG",
    "CNG1",
    "DP",
    "DST_MODID_5",
    "DST_MODID_6",
    "DST_MODID_LS",
    "DST_MODID_MGIDH",
    "DST_PORT",
    "DST_PORT_MGIDL",
    "DST_T",
    "DST_TGID",
    "HDR_EXT_LEN",
    "HEADER_TYPE",
    "HGI",
    "INGRESS_TAGGED",
    "L3",
    "LABEL_PRESENT",
    "LBID",
    "MCST",
    "MIRROR",
    "MIRROR_DONE",
    "MIRROR_ONLY",
    "OPCODE",
    "PFM",
    "PPD_DATA",
    "PPD_TYPE",
    "PRIORITY",
    "SRC_MODID",
    "SRC_MODID_5",
    "SRC_MODID_6",
    "SRC_MODID_LS",
    "SRC_PID",
    "SRC_PORT_TGID",
    "START",
    "TC",
    "VC_LABEL",
    "VTAG",
    "{:PPD_TYPE:0}PPD0:DST_T",
    "{:PPD_TYPE:0}PPD0:DST_TGID",
    "{:PPD_TYPE:0}PPD0:HDR_EXT_LEN",
    "{:PPD_TYPE:0}PPD0:INGRESS_TAGGED",
    "{:PPD_TYPE:0}PPD0:L3",
    "{:PPD_TYPE:0}PPD0:LABEL_OVERLAY_TYPE",
    "{:PPD_TYPE:0}PPD0:LABEL_PRESENT",
    "{:PPD_TYPE:0}PPD0:MIRROR",
    "{:PPD_TYPE:0}PPD0:MIRROR_CLASSIFICATION_TAG",
    "{:PPD_TYPE:0}PPD0:MIRROR_DONE",
    "{:PPD_TYPE:0}PPD0:MIRROR_ONLY",
    "{:PPD_TYPE:0}PPD0:OPCODE",
    "{:PPD_TYPE:0}PPD0:ORIG_SRC_MODID",
    "{:PPD_TYPE:0}PPD0:ORIG_SRC_PORT",
    "{:PPD_TYPE:0}PPD0:PFM",
    "{:PPD_TYPE:0}PPD0:PRESERVE_DOT1P",
    "{:PPD_TYPE:0}PPD0:PRESERVE_DSCP",
    "{:PPD_TYPE:0}PPD0:RSVD_4_0",
    "{:PPD_TYPE:0}PPD0:SRC_T",
    "{:PPD_TYPE:0}PPD0:VC_LABEL",
    "{:PPD_TYPE:0}PPD0:VC_LABEL_19_16",
    "{:PPD_TYPE:0}PPD0:VID_HIGH",
    "{:PPD_TYPE:0}PPD0:VID_LOW",
    "{:PPD_TYPE:1}PPD1:CLASSIFICATION_TAG",
    "{:PPD_TYPE:1}PPD1:HDR_EXT_LEN",
    "{:PPD_TYPE:1}PPD1:OPCODE",
    "{:PPD_TYPE:1}PPD1:PFM",
    "{:PPD_TYPE:1}PPD1:RSVD_12_11",
    "{:PPD_TYPE:1}PPD1:RSVD_48_32",
    "{:PPD_TYPE:1}PPD1:RSVD_4_0",
    "{:PPD_TYPE:1}PPD1:SRC_T",
    "{:PPD_TYPE:1}PPD1:VID_HIGH",
    "{:PPD_TYPE:1}PPD1:VID_LOW",
    "{:PPD_TYPE:2}PPD2:DEST_TYPE",
    "{:PPD_TYPE:2}PPD2:DEST_VP",
    "{:PPD_TYPE:2}PPD2:DO_NOT_LEARN",
    "{:PPD_TYPE:2}PPD2:DO_NOT_MODIFY",
    "{:PPD_TYPE:2}PPD2:FWD_TYPE",
    "{:PPD_TYPE:2}PPD2:LAG_FAILOVER",
    "{:PPD_TYPE:2}PPD2:MIRROR",
    "{:PPD_TYPE:2}PPD2:MULTIPOINT",
    "{:PPD_TYPE:2}PPD2:OPCODE",
    "{:PPD_TYPE:2}PPD2:PRESERVE_DOT1P",
    "{:PPD_TYPE:2}PPD2:PRESERVE_DSCP",
    "{:PPD_TYPE:2}PPD2:RSVD_11",
    "{:PPD_TYPE:2}PPD2:RSVD_7_6",
    "{:PPD_TYPE:2}PPD2:SOURCE_TYPE",
    "{:PPD_TYPE:2}PPD2:SOURCE_VP",
    "{:PPD_TYPE:2}PPD2:VNI_HIGH",
    "{:PPD_TYPE:2}PPD2:VNI_LOW",
    "{:PPD_TYPE:2}PPD2:VNI_MID",
    "{:PPD_TYPE:3}PPD3:DO_NOT_LEARN",
    "{:PPD_TYPE:3}PPD3:OPCODE",
    "{:PPD_TYPE:3}PPD3:PPD3_CONTAINER_TYPE",
    "{:PPD_TYPE:3}PPD3:PPD3_DATA_CONTAINER",
    "{:PPD_TYPE:3}PPD3:PRESERVE_DOT1P",
    "{:PPD_TYPE:3}PPD3:PRESERVE_DSCP",
    "{:PPD_TYPE:3}PPD3:RSVD_28",
    "{:PPD_TYPE:3}PPD3:RSVD_7_4",
    "{:PPD_TYPE:3}PPD3:SOURCE_INFO",
    "{:PPD_TYPE:3}PPD3:SOURCE_TYPE",
};

#endif
#endif /* CDK_CONFIG_INCLUDE_FIELD_INFO */



/*******************************************************************************
 *
 * The following is the symbol table itself. 
 * It defines the entries for all registers and memories.
 * It also incorporates the field information for each register and memory if
 * applicable.
 *
 ******************************************************************************/
static cdk_symbol_t higig_syms[] = {
{
	0,
#if  CDK_CONFIG_INCLUDE_FIELD_INFO == 1
	HIGIG_fields,
#endif
	 CDK_SYMBOL_INDEX_SIZE_ENCODE(12),
	0 | CDK_SYMBOL_FLAG_BIG_ENDIAN,
	"HIGIG",
#if  CDK_CONFIG_INCLUDE_ALIAS_NAMES == 1
	0,
	0
#endif
},
{
	0,
#if  CDK_CONFIG_INCLUDE_FIELD_INFO == 1
	HIGIG2_fields,
#endif
	 CDK_SYMBOL_INDEX_SIZE_ENCODE(16),
	0 | CDK_SYMBOL_FLAG_BIG_ENDIAN,
	"HIGIG2",
#if  CDK_CONFIG_INCLUDE_ALIAS_NAMES == 1
	0,
	0
#endif
},
};


cdk_symbols_t higig_symbols = 
{
   higig_syms, sizeof(higig_syms)/sizeof(higig_syms[0]),
#if CDK_CONFIG_INCLUDE_FIELD_NAMES == 1
   higig_fields
#else
   NULL
#endif
/* END OF SYMBOL FILE */
};

#endif /* CDK_CONFIG_INCLUDE_CHIP_SYMBOLS */
