/**
   @copyright
   Copyright (c) 2008 - 2014, INSIDE Secure Oy. All rights reserved.
*/

/**
   This is the executive-config.h header file for the Cavium
   Simple Executive based parts of QuickSec. See OCTEON-SDK
   for detailed documentation.
*/

#ifndef EXECUTIVE_CONFIG_H
#define EXECUTIVE_CONFIG_H
#define CVMX_ENABLE_PKO_FUNCTIONS 1
#define CVMX_ENABLE_HELPER_FUNCTIONS 1
#define CVMX_HELPER_FIRST_MBUFF_SKIP 184
#define CVMX_HELPER_NOT_FIRST_MBUFF_SKIP 0
#define CVMX_HELPER_ENABLE_BACK_PRESSURE 1
#define CVMX_HELPER_ENABLE_IPD 1
#define CVMX_HELPER_INPUT_TAG_TYPE CVMX_POW_TAG_TYPE_ORDERED
#define CVMX_HELPER_INPUT_TAG_IPV6_SRC_IP 0
#define CVMX_HELPER_INPUT_TAG_IPV6_DST_IP 0
#define CVMX_HELPER_INPUT_TAG_IPV6_SRC_PORT 0
#define CVMX_HELPER_INPUT_TAG_IPV6_DST_PORT 0
#define CVMX_HELPER_INPUT_TAG_IPV6_NEXT_HEADER 0
#define CVMX_HELPER_INPUT_TAG_IPV4_SRC_IP 0
#define CVMX_HELPER_INPUT_TAG_IPV4_DST_IP 0
#define CVMX_HELPER_INPUT_TAG_IPV4_SRC_PORT 0
#define CVMX_HELPER_INPUT_TAG_IPV4_DST_PORT 0
#define CVMX_HELPER_INPUT_TAG_IPV4_PROTOCOL 0
#define CVMX_HELPER_INPUT_TAG_INPUT_PORT 1
#define CVMX_HELPER_INPUT_PORT_SKIP_MODE CVMX_PIP_PORT_CFG_MODE_SKIPL2
#define CVMX_HELPER_PKO_QUEUES_PER_PORT_INTERFACE0 1
#define CVMX_HELPER_PKO_QUEUES_PER_PORT_INTERFACE1 1
#define CVMX_HELPER_DISABLE_RGMII_BACKPRESSURE 1
#define CVMX_HELPER_DISABLE_SPI4000_BACKPRESSURE 1
#define CVMX_HELPER_SPI_TIMEOUT 10
#define CVMX_LLM_CONFIG_NUM_PORTS 2
#define CVMX_ENABLE_LEN_M8_FIX 1
#define CVMX_CONFIG_NULL_POINTER_PROTECT 1
#define CVMX_CONFIG_ENABLE_DEBUG_PRINTS 1
#include "cvmx-resources.config"
#endif /* EXECUTIVE_CONFIG_H */
