/**
   @copyright
   Copyright (c) 2014, INSIDE Secure Oy. All rights reserved.
*/

#include "sshincludes.h"
#include "isakmp.h"

#define SSH_DEBUG_MODULE "SshIkeStringPacketPayload"


/* Notify payloads to packet descriptions */
const SshKeywordStruct ssh_ike_notify_payload_to_string_table[] = {
  { "N(RESERVED)",
    SSH_IKE_NOTIFY_MESSAGE_RESERVED },
  { "N(INVALID_PAYLOAD_TYPE)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_PAYLOAD_TYPE },
  { "N(DOI_NOT_SUPPORTED)",
    SSH_IKE_NOTIFY_MESSAGE_DOI_NOT_SUPPORTED },
  { "N(SITUATION_NOT_SUPPORTED)",
    SSH_IKE_NOTIFY_MESSAGE_SITUATION_NOT_SUPPORTED },
  { "N(INVALID_COOKIE)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_COOKIE },
  { "N(INVALID_MAJOR_VERSION)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_MAJOR_VERSION },
  { "N(INVALID_MINOR_VERSION)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_MINOR_VERSION },
  { "N(INVALID_EXCHANGE_TYPE)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_EXCHANGE_TYPE },
  { "N(INVALID_FLAGS)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_FLAGS },
  { "N(INVALID_MESSAGE_ID)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_MESSAGE_ID },
  { "N(INVALID_PROTOCOL_ID)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_PROTOCOL_ID },
  { "N(INVALID_SPI)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_SPI },
  { "N(INVALID_TRANSFORM_ID)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_TRANSFORM_ID },
  { "N(ATTRIBUTES_NOT_SUPPORTED)",
    SSH_IKE_NOTIFY_MESSAGE_ATTRIBUTES_NOT_SUPPORTED },
  { "N(NO_PROPOSAL_CHOSEN)",
    SSH_IKE_NOTIFY_MESSAGE_NO_PROPOSAL_CHOSEN },
  { "N(BAD_PROPOSAL_SYNTAX)",
    SSH_IKE_NOTIFY_MESSAGE_BAD_PROPOSAL_SYNTAX },
  { "N(PAYLOAD_MALFORMED)",
    SSH_IKE_NOTIFY_MESSAGE_PAYLOAD_MALFORMED },
  { "N(INVALID_KEY_INFORMATION)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_KEY_INFORMATION },
  { "N(INVALID_ID_INFORMATION)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_ID_INFORMATION },
  { "N(INVALID_CERT_ENCODING)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_CERT_ENCODING },
  { "N(INVALID_CERTIFICATE)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_CERTIFICATE },
  { "N(CERT_TYPE_UNSUPPORTED)",
    SSH_IKE_NOTIFY_MESSAGE_CERT_TYPE_UNSUPPORTED },
  { "N(INVALID_CERT_AUTHORITY)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_CERT_AUTHORITY },
  { "N(INVALID_HASH_INFORMATION)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_HASH_INFORMATION },
  { "N(AUTHENTICATION_FAILED)",
    SSH_IKE_NOTIFY_MESSAGE_AUTHENTICATION_FAILED },
  { "N(INVALID_SIGNATURE)",
    SSH_IKE_NOTIFY_MESSAGE_INVALID_SIGNATURE },
  { "N(ADDRESS_NOTIFICATION)",
    SSH_IKE_NOTIFY_MESSAGE_ADDRESS_NOTIFICATION },
  { "N(SA_LIFETIME)",
    SSH_IKE_NOTIFY_MESSAGE_SA_LIFETIME },
  { "N(CERTIFICATE_UNAVAILABLE)",
    SSH_IKE_NOTIFY_MESSAGE_CERTIFICATE_UNAVAILABLE },
  { "N(UNSUPPORTED_EXCHANGE_TYPE)",
    SSH_IKE_NOTIFY_MESSAGE_UNSUPPORTED_EXCHANGE_TYPE },
  { "N(UNEQUAL_PAYLOAD_LENGTHS)",
    SSH_IKE_NOTIFY_MESSAGE_UNEQUAL_PAYLOAD_LENGTHS },
  { "N(NO_SA_ESTABLISHED)",
    SSH_IKE_NOTIFY_MESSAGE_NO_SA_ESTABLISHED },
  { "N(NO_STATE_MATCHED)",
    SSH_IKE_NOTIFY_MESSAGE_NO_STATE_MATCHED },
  { "N(EXCHANGE_DATA_MISSING)",
    SSH_IKE_NOTIFY_MESSAGE_EXCHANGE_DATA_MISSING },
  { "N(TIMEOUT)",
    SSH_IKE_NOTIFY_MESSAGE_TIMEOUT },
  { "N(DELETED)",
    SSH_IKE_NOTIFY_MESSAGE_DELETED },
  { "N(ABORTED)",
    SSH_IKE_NOTIFY_MESSAGE_ABORTED },
  { "N(UDP_HOST_UNREACHABLE)",
    SSH_IKE_NOTIFY_MESSAGE_UDP_HOST_UNREACHABLE },
  { "N(UDP_PORT_UNREACHABLE)",
    SSH_IKE_NOTIFY_MESSAGE_UDP_PORT_UNREACHABLE },
  { "N(OUT_OF_MEMORY)",
    SSH_IKE_NOTIFY_MESSAGE_OUT_OF_MEMORY },
  { "N(CONNECTED)",
    SSH_IKE_NOTIFY_MESSAGE_CONNECTED },
  { "N(RESPONDER_LIFETIME)",
    SSH_IKE_NOTIFY_MESSAGE_RESPONDER_LIFETIME },
  { "N(REPLAY_STATUS)",
    SSH_IKE_NOTIFY_MESSAGE_REPLAY_STATUS },
  { "N(INITIAL_CONTACT)",
    SSH_IKE_NOTIFY_MESSAGE_INITIAL_CONTACT },
  { "N(R_U_THERE)",
    SSH_IKE_NOTIFY_MESSAGE_R_U_THERE },
  { "N(R_U_THERE_ACK)",
    SSH_IKE_NOTIFY_MESSAGE_R_U_THERE_ACK },
  { "N(CISCO_PSK_HASH)",
    SSH_IKE_NOTIFY_MESSAGE_CISCO_PSK_HASH },
  { "N(RETRY_LATER)",
    SSH_IKE_NOTIFY_MESSAGE_RETRY_LATER },
  { "N(RETRY_NOW)",
    SSH_IKE_NOTIFY_MESSAGE_RETRY_NOW },
  { NULL, 0 }
};

/* Packet payloads to packet descriptions */
const SshKeywordStruct ssh_ike_packets_payload_to_string_table[] = {
  { "NONE",
    SSH_IKE_PAYLOAD_TYPE_NONE },
  { "SA",
    SSH_IKE_PAYLOAD_TYPE_SA },
  { "P",
    SSH_IKE_PAYLOAD_TYPE_P },
  { "T",
    SSH_IKE_PAYLOAD_TYPE_T },
  { "KE",
    SSH_IKE_PAYLOAD_TYPE_KE },
  { "ID",
    SSH_IKE_PAYLOAD_TYPE_ID },
  { "CERT",
    SSH_IKE_PAYLOAD_TYPE_CERT },
  { "CR",
    SSH_IKE_PAYLOAD_TYPE_CR },
  { "HASH",
    SSH_IKE_PAYLOAD_TYPE_HASH },
  { "SIG",
    SSH_IKE_PAYLOAD_TYPE_SIG },
  { "Nonce",
    SSH_IKE_PAYLOAD_TYPE_NONCE },
  { "N",
    SSH_IKE_PAYLOAD_TYPE_N },
  { "DEL",
    SSH_IKE_PAYLOAD_TYPE_D },
  { "Vid",
    SSH_IKE_PAYLOAD_TYPE_VID },
  { "ATTR",
    SSH_IKE_PAYLOAD_TYPE_ATTR },
  { "MAX",
    SSH_IKE_PAYLOAD_TYPE_MAX },
  { "PRV",
    SSH_IKE_PAYLOAD_TYPE_PRV },
  { NULL, 0 }
};


const char *
ssh_ikev1_notify_payload_to_string(SshIkeNotifyMessageType type)
{
  const char *name;

  name = ssh_find_keyword_name(ssh_ike_notify_payload_to_string_table,
                               type);
  if (name == NULL)
    return "unknown";

  return name;
}

const char *
ssh_ikev1_packet_payload_to_string(SshIkePayloadType type)
{
  const char *name;

  name = ssh_find_keyword_name(ssh_ike_packets_payload_to_string_table,
                               type);
  if (name == NULL)
    return "unknown";

  return name;
}

