/**
   @copyright
   Copyright (c) 2002 - 2014, INSIDE Secure Oy. All rights reserved.
*/

/**
   Notify message definitions.
*/

#ifndef ISAKMP_NOTIFY_H
#define ISAKMP_NOTIFY_H

typedef enum {
  SSH_IKE_NOTIFY_CLASSES_TYPE_OF_OFFENDING_PAYLOAD = 3,
  SSH_IKE_NOTIFY_CLASSES_OFFENDING_PAYLOAD_DATA = 4,
  SSH_IKE_NOTIFY_CLASSES_ERROR_POSITION_OFFSET = 5,
  SSH_IKE_NOTIFY_CLASSES_ERROR_TEXT = 6,
  SSH_IKE_NOTIFY_CLASSES_ERROR_TEXT_LANGUAGE = 7,
  SSH_IKE_NOTIFY_CLASSES_MESSAGE_ID = 8,
  SSH_IKE_NOTIFY_CLASSES_EXCHANGE_TYPE = 9,
  SSH_IKE_NOTIFY_CLASSES_INVALID_FLAG_BITS = 10,
  SSH_IKE_NOTIFY_CLASSES_SUGGESTED_PROPOSAL = 11,
  SSH_IKE_NOTIFY_CLASSES_VERSION = 12
} SshIkeNotifyAttributeClasses;

typedef enum {
  SSH_IKE_NOTIFY_VALUES_VERSION_1 = 1
} SshIkeNotifyValuesNotificationAttributeVersion;

#endif /* ISAKMP_NOTIFY_H */
