# Broadcom ARM platform
export RT-N18U_BASE := IPV6SUPP=y HTTPS=y ARM=y NTFS="paragon" HFS="paragon" AUTODICT=y BBEXTRAS=y USBEXTRAS=y EBTABLES=y SAMBA3=3.6.x MEDIASRV=y MODEM=y PARENTAL2=y ACCEL_PPTPD=y PRINTER=y WEBDAV=y SMARTSYNCBASE=y USB="USB" GRO=y APP="installed" PROXYSTA=y DNSMQ=y SHP=y NVRAM_64K=y BCMWL6=y BCMWL6A=y BCM4708=y BCM5301X=y DISK_MONITOR=y LANWAN_LED=y OPTIMIZE_XBOX=y ODMPID=y XHCI=y DUALWAN=y REPEATER=y ARMCPUSMP=up NEW_USER_LOW_RSSI=y OPENVPN=y TIMEMACHINE=y MDNS=y VPNC=y BRCM_NAND_JFFS2=y JFFS2LOG=y XHCIMODE=y DEBUGFS=y STAINFO=y BCM5301X_TRAFFIC_MONITOR=y DUMP_OOPS_MSG=y BCM_RECVFILE=n LINUX_MTD="64" REBOOT_SCHEDULE=y MULTICASTIPTV=y QUAGGA=y YANDEXDNS=y LAN50=y ATCOVER=y GETREALIP=y SW_HW_AUTH=y NATNL_AIHOME=y NVRAM_ENCRYPT=50018 UTF8_SSID=y
export RT-N18U := BUILD_NAME="RT-N18U" RTN18U=y $(RT-N18U_BASE) FAKEHDR=y FORCE_SN=65535 FORCE_EN=65535 \
		DNSFILTER=y DNSPRIVACY=y OPENSSL11=y BTN_WPS_ALLLED=y CAPTCHA=y EXT4FS=y \
		HD_SPINDOWN=y LETSENCRYPT=y SSH=y SYSSTATE=y NTPD=y RSYSLOGD=y \
		MERLINUPDATE=y NFS=y SNMPD=y TOR=y UPNPIGD2=n NANO=y \
		NETOOL=y TRACEROUTE=y
